### ISSUE TITLE
Error in exp02.py

### ISSUE THREAD

**Issue by akshayag** [gongzhitaao/tensorflow-adversarial#1]
TypeError: call() got an unexpected keyword argument 'logits'

**Comment by gongzhitaao** [comment]
Could you please provide more information? I didn't find `logits` argument in `ex_02.py`, if this is what you referred to.  I think I run it and it works.

**Comment by Poomathi** [comment]
Hi - Even I got the same error in ex_02.py.
Traceback (most recent call last):
  File "RMLtgma.py", line 101, in <module>
    print('\nTraining model')
  File "/home/pduraisamy/test/adversarial/tgsm.py", line 56, in tgsm
    name='tgsm')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/pduraisamy/test/adversarial/tgsm.py", line 46, in _body
    ybar, logits = model(x_adv, logits=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
TypeError: call() got an unexpected keyword argument 'logits'

**Comment by gongzhitaao** [comment]
I got it, I fixed in my local repo without push it.  Should be fixed in ec3d382.

**Comment by Poomathi** [comment]
Thanks. It works now. Really appreciate your quick response.
